#!/usr/bin/env python3
import os
import sys
import shutil

def stow(source, target, adopt=False):
    if os.path.isfile(source):
        if not os.path.exists(target):
            os.symlink(source, target)
        elif not adopt:
            print(f"File {target} already exists. Exiting.")
            sys.exit(1)
        else:  # copy target file to source
            shutil.copy(target, source)
    elif os.path.isdir(source):
        if not os.path.exists(target):
            os.makedirs(target)
        for filename in os.listdir(source):
            stow(
                os.path.join(source, filename),
                os.path.join(target, filename),
                adopt,
            )

stow(*sys.argv[1:])