# brew bundle
# https://github.com/Homebrew/homebrew-bundle
tap 'homebrew/cask-fonts'
tap 'ethereum/ethereum'

brew 'cmake'
brew 'fd'
brew 'fx'
brew 'himalaya'
brew 'keepassxc'
brew 'mas'
brew 'plantuml'
brew 'stow'
brew 'yazi'

cask 'espanso'
cask 'iterm2'
cask 'lulu'

# cli
brew 'fzf'
brew 'git'
brew 'git-crypt'
brew 'ripgrep'
## test
brew 'dasel'
brew 'hurl'
brew 'eza'
cask 'mitmproxy'
brew 'git-bug'