alias htmlmd="pandoc -f html -t markdown"
alias ml="himalaya"
alias mlb="himalaya -a psg"
alias mlc="himalaya -a cy"
alias r='. ranger'
alias l='eza'
alias ls='eza'
alias ll='eza -l'
alias la='eza -la'
alias xls='/bin/ls'
alias cat='bat'
alias xcat='/bin/cat'
alias z='zoxide'
alias xcd='/bin/cd'